# Generated by Django 6.0.3 on 2026-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_remove_post_image_name_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(blank=True, default='', help_text='e.g. gta-6.jpg', max_length=100),
        ),
    ]
